# Práctica 3: Algoritmos basados en árboles para la predicción de cardiopatía

## Importar librerías

In [1]:
%pip install -q kagglehub

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

## Importar datos

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("fedesoriano/heart-failure-prediction")

df = pd.read_csv(path + "/heart.csv")

## Análisis exploratorio de datos (EDA)

In [4]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [6]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [7]:
df.describe(include='object')

Sex ChestPainType RestingECG ExerciseAngina ST_Slope
count   918           918        918            918      918
unique    2             4          3              2        3
top       M           ASY     Normal              N     Flat
freq    725           496        552            547      460

In [8]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [9]:
# Varaibles numéricas y categóricas

numericas = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categoricas = df.select_dtypes(include=['object', 'category']).columns.tolist()

print("Variables numéricas:", numericas)
print("\nVariables categóricas:", categoricas)


Variables numéricas: ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak', 'HeartDisease']

Variables categóricas: ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']


In [10]:
# Distribución de la variable objetivo

figure = df["HeartDisease"].value_counts().reset_index()
figure.columns = ['HeartDisease', 'Cuenta']
figure['Porcentaje'] = (figure['Cuenta'] / figure['Cuenta'].sum()) * 100
print(figure)

   HeartDisease  Cuenta  Porcentaje
0             1     508   55.337691
1             0     410   44.662309


In [11]:
# Estadísticas descriptivas de la variable objetivo (solo columnas numéricas) excluyendo la variable objetivo
df.groupby('HeartDisease')[numericas].mean().drop(columns=['HeartDisease']) 

Age   RestingBP  Cholesterol  FastingBS       MaxHR  \
HeartDisease                                                              
0             50.551220  130.180488   227.121951   0.107317  148.151220   
1             55.899606  134.185039   175.940945   0.334646  127.655512   

               Oldpeak  
HeartDisease            
0             0.408049  
1             1.274213

### Preprocesamiento de datos

In [12]:
# Codificación de variables categóricas LabelEncoder
le = LabelEncoder()
for col in categoricas:
    df[col] = le.fit_transform(df[col])
    
df.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    1              1        140          289          0           1   
1   49    0              2        160          180          0           1   
2   37    1              1        130          283          0           2   
3   48    0              0        138          214          0           1   
4   54    1              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

In [13]:
# Separación de conjuntos de entrenamiento y prueba
X = df.drop('HeartDisease', axis=1)
y = df['HeartDisease']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Árbol de decisión para clasificación

In [14]:
seed = 42
np.random.seed(seed)

# Entretar árbol de decisión sin restricciones
dtc = DecisionTreeClassifier(random_state=42)
dtc.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [19]:
# Analizar profundidad del árbol, número de nodos y hojas y precisión en entrenamiento y prueba
print("Profundidad del árbol:", dtc.get_depth())
print("Número de nodos:", dtc.tree_.node_count)
print("Número de hojas:", dtc.get_n_leaves())

train_accuracy = dtc.score(X_train, y_train)
test_accuracy = dtc.score(X_test, y_test)

print("Precisión en entrenamiento:", train_accuracy)
print("Precisión en prueba:", test_accuracy)

Profundidad del árbol: 15
Número de nodos: 209
Número de hojas: 105
Precisión en entrenamiento: 1.0
Precisión en prueba: 0.782608695652174


Según los resultados, el árbol de decisión sin restricciones tiene una profundidad de 15, con 209 nodos y 105 hojas.
La precisión en el conjunto de entrenamiento es del 100%, lo que indica un sobreajuste, mientras que la precisión en el conjunto de prueba es del 78.26%.

In [26]:
# Analizar si el modelo presenta sobreajuste
y_pred = dtc.predict(X_test)
print("Reporte de clasificación:\n", classification_report(y_test, y_pred))
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred))
roc_auc = roc_auc_score(y_test, dtc.predict_proba(X_test)[:, 1])
print("\nROC AUC:", roc_auc)

print("\nNo HeartDisease clasificado como No HeartDisease", sum((y_test == 0) & (y_pred == 0)))
print("No HeartDisease clasificado como HeartDisease", sum((y_test == 0) & (y_pred == 1)))
print("HeartDisease clasificado como No HeartDisease", sum((y_test == 1) & (y_pred == 0)))
print("HeartDisease clasificado como HeartDisease", sum((y_test == 1) & (y_pred == 1)))

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.70      0.83      0.76        77
           1       0.86      0.75      0.80       107

    accuracy                           0.78       184
   macro avg       0.78      0.79      0.78       184
weighted avg       0.79      0.78      0.78       184

Matriz de confusión:
 [[64 13]
 [27 80]]

ROC AUC: 0.7894161912853502

No HeartDisease clasificado como No HeartDisease 64
No HeartDisease clasificado como HeartDisease 13
HeartDisease clasificado como No HeartDisease 27
HeartDisease clasificado como HeartDisease 80


Con las métricas ROC AUC, precisión, recall y F1-score, podemos evaluar mejor el rendimiento del modelo, determinando si hay sobreajuste y considerando el equilibrio entre clases en el conjunto de datos.
En este caso, el modelo muestra un buen rendimiento en ambas clases, pero hay margen de mejora, especialmente en la clase minoritaria (HeartDisease = 0).